### ISSUE TITLE
GithubのWikiに作ったアプリの設計書を添付する

### ISSUE THREAD

**Issue by fuchi0741** [masayatoida/ChildStock#1]

**Comment by fuchi0741** [comment]
@masayatoida 
すいません。リンク押下後でなく画像を直接見れるようにしたいです🙏
修正お願いします！

**Comment by fuchi0741** [comment]
<img width="1434" alt="APP設計書" src="https://user-images.githubusercontent.com/50318372/145698562-6697ea55-c114-4ea0-986b-3b28c69c68ca.png">

**Comment by masayatoida** [comment]
直接画像添付しました。
