### ISSUE TITLE
PR作成時のテンプレを設定

### ISSUE THREAD

**Issue by fuchi0741** [masayatoida/ChildStock#10]
以下のURLを参考にPR作成時にPRテンプレが表示できるようにしてください。
https://dev.classmethod.jp/articles/pull-request-template/

------------↓がPRテンプレです----------------

## コマンド
git checkout -b 該当ブランチ名 origin/該当ブランチ名
※ 該当ブランチ名は各自変更してください

## セルフレビュー
レビュー依頼の前に確認をしてください:bulb:

- [ ] 期待通りの挙動をするか?
- [ ] タイポしていないか？
- [ ] warningが新たに増えていないか？
- [ ] リファクタリングできる余地がないか?
- [ ] コンフリクトが発生してないか？
- [ ] UIのレイアウトが崩れていないか？ ※UIを実装した場合のみでOK

すべて:white_check_mark:をつけたら、レビューを依頼しましょう！:+1:
 
## 環境
Xcode...

**Comment by masayatoida** [comment]
@fuchi0741 
ファイルの作成はできましたがコマンドや概要という文字が、太文字にできていないと思うのですが修正すべきでしょうか？

**Comment by fuchi0741** [comment]
@masayatoida 

> 太文字にできていないと思うのですが修正すべきでしょうか？

Githubだとマークダウン反映済みだっため、反映前のものをSlackに添付しました！
https://fuchihq.slack.com/archives/D02CPCS245R/p1641044410001200

**Comment by masayatoida** [comment]
@fuchi0741 
完了したためクローズします！
